### ISSUE TITLE
Build host config used instead of target (re, src/dns/darwin/srv.c)

### ISSUE THREAD

**Issue by gdt** [juha-h/libbaresip-android#10]
After local patches to set the toolchain to darwin- and add /opt/pkg/bin to the PATH, the build fails with the following.  It appears that some Makefile is choosing a host version of srv.c, rather than switching on the cross target.

```
  CC      build-arm/dns/dname.o
  CC      build-arm/dns/hdr.o
  CC      build-arm/dns/ns.o
  CC      build-arm/dns/rr.o
  CC      build-arm/dns/rrlist.o
  CC      build-arm/dns/darwin/srv.o
src/dns/darwin/srv.c:14:10: fatal error: 'SystemConfiguration/SystemConfiguration.h' file not found
#include <SystemConfiguration/SystemConfiguration.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [build-arm/dns/darwin/srv.o] Error 1
make[1]: *** [libre.a] Error 2
make: *** [default] Error 2
```

**Comment by mateuszs7** [comment]
I had the same problem. You have to change the OS setting in Makefile from 
`OS		    := $(shell uname -s | tr "[A-Z]" "[a-z]")`
to
`OS		    := linux`

After that there was a problem to correctly resolve `ar` path. So I changed name of the program for linux os and it compiled.
File: re/mk/re.mk:
```
ifeq ($(OS),linux)
	CFLAGS		+= -fPIC -DLINUX
	LIBS		+= -ldl
	LFLAGS		+= -fPIC
	SH_LFLAGS	+= -shared
	MOD_LFLAGS	+=
	APP_LFLAGS	+= -rdynamic
	AR		:= ar
	AFLAGS		:= crD
endif

to 

ifeq ($(OS),linux)
	CFLAGS		+= -fPIC -DLINUX
	LIBS		+= -ldl
	LFLAGS		+= -fPIC
	SH_LFLAGS	+= -shared
	MOD_LFLAGS	+=
	APP_LFLAGS	+= -rdynamic
	AR		:= aarch64-linux-android-ar
	AFLAGS		:= crD
endif

**Comment by juha-h** [comment]
It is OK with me to hardcode OS to linux in Makefile, but I cannot do anything with re.  You would need to submit pull request to re.
