### ISSUE TITLE
Build error, it displayed no rule for disclean 

### ISSUE THREAD

**Issue by wisenight** [juha-h/libbaresip-android#13]
Hi, Sir

I try to build this project, with my ubuntu 20.04, ndk r21d
But, it will show below error, is this error just warning?
make[2]: *** No rule to make target 'distclean'. Stop.

**Comment by juha-h** [comment]
wisenight writes:

> I try to build this project, with my ubuntu 20.04, ndk r21d
> But, it will show below error, is this error just warning?
> make[2]: *** No rule to make target 'distclean'. Stop.

How are you trying to build the project?  If you use
```
make clean
```
find out which distclean gives the error.

**Comment by juha-h** [comment]
Cannot reproduce this. Closed due to lack of further information.
