### ISSUE TITLE
i couldn't build

### ISSUE THREAD

**Issue by MS-ELEX** [juha-h/libbaresip-android#14]
I tried make.
I succeeded to STEP3. 
but STEP4 make install-all

`make install-all
make install ANDROID_TARGET_ARCH=armeabi-v7a
make[1]: ディレクトリ '/home/karikomi/AndroidStudioProjects/libbaresip-android' に入ります
make distclean -C openssl
make[2]: ディレクトリ '/home/karikomi/AndroidStudioProjects/libbaresip-android/openssl' に入ります
make[2]: *** ターゲット 'distclean' を make するルールがありません. 中止.
make[2]: ディレクトリ '/home/karikomi/AndroidStudioProjects/libbaresip-android/openssl' から出ます
make[1]: [Makefile:126: openssl] エラー 2 (無視されました)
cd openssl && \
CC=clang ANDROID_NDK=/home/karikomi/Android/Sdk/ndk-bundle PATH=/home/karikomi/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin:/usr/bin:/bin ./Configure android-arm no-shared -D__ANDROID_API__=21 && \
CC=clang ANDROID_NDK=/home/karikomi/Android/Sdk/ndk-bundle PATH=/home/karikomi/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin:/usr/bin:/bin make build_libs
Configuring OpenSSL version 1.1.1h-dev (0x10101080L) for android-arm
Using os-specific seed configuration
$ANDROID_NDK_HOME=/home/karikomi/Android/Sdk/ndk-bundle is invalid at (eval 10) line 37.
make[1]: *** [Makefile:127: openssl] エラー 2
make[1]: ディレクトリ '/home/karikomi/AndroidStudioProjects/libbaresip-android' から出ます
make: *** [Makefile:308: install-all] エラー 2
karikomi@VM-Ubuntu:~/AndroidStudioProjects/libbaresip-android$`

**Comment by juha-h** [comment]
y.karikomi writes:

> Configuring OpenSSL version 1.1.1h-dev (0x10101080L) for android-arm
> Using os-specific seed configuration
> $ANDROID_NDK_HOME=/home/karikomi/Android/Sdk/ndk-bundle is invalid at (eval 10) line 37.

Looks like there is something wrong with your ndk-bundle.

I cannot really help with these kind of build issues that are not
related to libbaresip-android project's Makefile, but to your build
environment.

Try to re-create your build environment.

I'll close this now.
