### ISSUE TITLE
How to make libbaresip android use alsa directly instead use opensl es ?

### ISSUE THREAD

**Issue by assegaf** [juha-h/libbaresip-android#15]
How to make libbaresip android use alsa directly instead use opensl es, just like libbaresip for linux ?
I need to directly write to pcm node using alsa library (tinyalsa) because some specification, so I need to make libbaresip dont use opensl es.

**Comment by juha-h** [comment]
assegaf writes:

> How to make libbaresip android use alsa directly instead use opensl
> es, just like libbaresip for linux ?
> I need to directly write to pcm node using alsa library (tinyalsa)
> because some specification, so I need to make libbaresip dont use
> opensl es.

This is not controlled by the lib, but by the app.  In config file, you
need to change these:
```
audio_player opensles,nil
audio_source opensles,nil
audio_alert opensles,nil
```

**Comment by assegaf** [comment]
ah great thanks ..

**Comment by assegaf** [comment]
will try it first before closing this issue, I have tried to remove the opensles from Makefile compilation but seem error later in app no codec on asterisk found

**Comment by assegaf** [comment]
with config changed to
audio_player alsa,nil
audio_source alsa,nil
audio_alert alsa,nil

@juha-h I tried to change this default device
# vim libbaresip-android/baresip/modules/alsa/alsa.c 
with the default is "default" which I know to hw:1,0, changed to :

...
char alsa_dev[64] = "hw:0,1";
..


but dont seem there any changes, the sound is still at hw1:0,  I even dont know if it changed from opensles to alsa directly, any how to know it ?

**Comment by juha-h** [comment]
I have never tried to use alsa audio in Android applications.  This
project currently only supports Android native audio based on OpenSLES.

Regarding configuring alsa device, I would try first with baresip Linux
app and once you get it done there, try next with Android.

**Comment by assegaf** [comment]
agree,  I will try first on linux because its still on logcat still using opensl es.

**Comment by assegaf** [comment]
I got the culprit, some how alsa.so its not generated, in this libbaresip-android, how it can possible.

logcat android
11-28 20:46:33.323 22359 22359 I Baresip : module alsa.so
11-28 20:46:33.378 22359 22395 D Baresip Lib: ./alsa.so
11-28 20:46:33.378 22359 22395 D Baresip Lib: dlopen failed: library "./alsa.so" not found
11-28 20:46:33.378 22359 22395 D Baresip Lib: module alsa.so: No such file or directory

I will focus on Makefile, some how skip alsa modules, binary not compile

nokideen@dhost:/media/sdc1/sandbox/libbaresip-android
$ find | grep opensles
./baresip/modules/opensles
./baresip/modules/opensles/module.mk
./baresip/modules/opensles/opensles.c
./baresip/modules/opensles/player.c
./baresip/modules/opensles/opensles.h
./baresip/modules/opensles/recorder.c
./baresip/build-arm/modules/opensles
./baresip/build-arm/modules/opensles/player.o
./baresip/build-arm/modules/opensles/player.d
./baresip/build-arm/modules/opensles/recorder.d
./baresip/build-arm/modules/opensles/opensles.o
./baresip/build-arm/modules/opensles/recorder.o
./baresip/build-arm/modules/opensles/opensles.d




nokideen@dhost:/media/sdc1/sandbox/libbaresip-android
$ find | grep alsa
./baresip/modules/alsa
./baresip/modules/alsa/module.mk
./baresip/modules/alsa/alsa_play.c
./baresip/modules/alsa/alsa.h
./baresip/modules/alsa/alsa_src.c
./baresip/modules/alsa/alsa.c

**Comment by juha-h** [comment]
assegaf writes:

> I got the culprit, some how alsa.so its not generated, in this
> libbaresip-android, how it can possible.

You need to add alsa to EXTRA_MODULES list:
```
EXTRA_MODULES := webrtc_aec opensles dtls_srtp opus ilbc g711 g722 \
	g7221 g726 g729 amr zrtp stun turn ice presence contact mwi account \
	natpmp srtp uuid debug_cmd avcodec avformat vp8 vp9 selfview
```

**Comment by assegaf** [comment]
ok got it, but need to make changes from lib asound  (alsa ) to tinyalsa .. I think need to make new modules rather than alsa which is linux, android is tinyalsa

**Comment by juha-h** [comment]
assegaf writes:

> ok got it, but need to make changes from lib asound  (alsa ) to
> tinyalsa .. I think need to make new modules rather than alsa which is
> linux, android is tinyalsa

OK, once you get tinyalsa module implemented/tested, make a pull request
to baresip project.

**Comment by assegaf** [comment]
got it, closed for now, not an issue/bug

**Comment by assegaf** [comment]
libbaresip-android succed built, 
I am stuck in baresip-studio asking to link the tinyalsa/asoundlib.h or the binary tinyalsa.so which arm64, where should I put it to make the build baresip-studio success ?

-- error log baresip-studio ---

/media/sdc1/sandbox/baresip-studio/app/src/main/cpp/../../../../distribution/baresip/lib/arm64-v8a/libbaresip.a(tinyalsa.o): In function `tinyalsa_close':
/media/sdc1/sandbox/libbaresip-android/baresip/modules/tinyalsa/tinyalsa.c:166: undefined reference to `snd_config_update_free_global'
/media/sdc1/sandbox/baresip-studio/app/src/main/cpp/../../../../distribution/baresip/lib/arm64-v8a/libbaresip.a(tinyalsa_src.o): In function `tinyalsa_src_alloc':
/media/sdc1/sandbox/libbaresip-android/baresip/modules/tinyalsa/tinyalsa_src.c:149: undefined reference to `pcm_open'
/media/sdc1/sandbox/libbaresip-android/baresip/modules/tinyalsa/tinyalsa_src.c:166: undefined reference to `snd_get_error'
/media/sdc1/sandbox/baresip-studio/app/src/main/cpp/../../../../distribution/baresip/lib/arm64-v8a/libbaresip.a(tinyalsa_src.o): In function `ausrc_destructor':
/media/sdc1/sandbox/libbaresip-android/baresip/modules/tinyalsa/tinyalsa_src.c:46: undefined reference to `pcm_close'
/media/sdc1/sandbox/baresip-studio/app/src/main/cpp/../../../../distribution/baresip/lib/arm64-v8a/libbaresip.a(tinyalsa_src.o): In function `read_thread':
/media/sdc1/sandbox/libbaresip-android/baresip/modules/tinyalsa/tinyalsa_src.c:63: undefined reference to `pcm_start'
/media/sdc1/sandbox/libbaresip-android/baresip/modules/tinyalsa/tinyalsa_src.c:65: undefined reference to `snd_get_error'
/media/sdc1/sandbox/libbaresip-android/baresip/modules/tinyalsa/tinyalsa_src.c:73: undefined reference to `pcm_read'
/media/sdc1/sandbox/libbaresip-android/baresip/modules/tinyalsa/tinyalsa_src.c:75: undefined reference to `pcm_prepare'
/media/sdc1/sandbox/baresip-studio/app/src/main/cpp/../../../../distribution/baresip/lib/arm64-v8a/libbaresip.a(tinyalsa_play.o): In function `tinyalsa_play_alloc':

**Comment by juha-h** [comment]
assegaf writes:

> I am stuck in baresip-studio asking to link the tinyalsa/asoundlib.h
> or the binary tinyalsa.so which arm64, where should I put it to make
> the build baresip-studio success ?

If tinyalsa is a new static library, you need to include it in
app/src/main/cpp/CMakeLists.txt and also add lines to libbaresip Makefile's
CFLAGS and LFLAGS.

**Comment by assegaf** [comment]
ah got it thanks, may I know how to change default sample rate from 8000 to 16000 ?
tried to change from "config" file : audio_srate 16000
seem no changes. ?

**Comment by juha-h** [comment]
assegaf writes:

> ah got it thanks, may I know how to change default sample rate from
> 8000 to 16000 ? 
> tried to change from "config" file : audio_srate 16000
> seem no changes. ?

Config vars audio_srate and audio_channels are not used anymore.
I'll remove from config.  Try auplay_srate and ausrc_srate.

**Comment by assegaf** [comment]
hi @juha-h I am stuck in writing tinyalsa_src, its always resulting in distorted sound (but I hear the recorded is there, but distorted, robotic too) when I try an echo test to asterisk, when I use module alsa, its running fine, so its about somehing variable related ?

is there anything I can learn about ?

the srate is 48000 and channel : 2 when I try this ...
