### ISSUE TITLE
question :  Automatic network roaming on Android

### ISSUE THREAD

**Issue by olirehacek** [juha-h/libbaresip-android#17]
Hi,
Is automatic network roaming supported on Android?
I am running into a few issues, while the phone is changing the network from wifi to LTE. 

Just looking for an answer if this is an issue in my particulate case or with baresip on Android.

Thank You !

**Comment by juha-h** [comment]
Ondrej Rehacek writes:

> Is automatic network roaming supported on Android?
> I am running into a few issues, while the phone is changing the
> network from wifi to LTE.  
> 
> Just looking for an answer if this is an issue in my particulate case
> or with baresip on Android.

libbaresip-android does not support automatic roaming.  it is the task
of android app to detect network changes and then use libbaresip android
to reconfigure the network.

**Comment by olirehacek** [comment]
> Ondrej Rehacek writes:
> Is automatic network roaming supported on Android? I am running into a few issues, while the phone is changing the network from wifi to LTE. Just looking for an answer if this is an issue in my particulate case or with baresip on Android.
> libbaresip-android does not support automatic roaming. it is the task of android app to detect network changes and then use libbaresip android to reconfigure the network.

Thank You Juha. Do you have some sort of recommended solution ? Does the “studio” app example you have implements this ?

**Comment by juha-h** [comment]
Ondrej Rehacek writes:

> Thank You Juha. Do you have some sort of recommended solution ? Does
> the “studio” app example you have implements this ?

Yes, it does. Check BaresipService.kt starting from line

cm = getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
