### ISSUE TITLE
Building video branch failing due to lack of some aclocal files

### ISSUE THREAD

**Issue by snachmsm** [juha-h/libbaresip-android#19]
Hi

I'm trying to build this project: got ndk21, fresh git pull and also fresh Ubuntu instance (using VM). I've changed two fields in Makefile:

`NDK_PATH  :=  /media/shared_vm/android-ndk-r21`
`OUTPUT_DIR := /media/shared_vm/out`

`shared_vm` is folder shared between Ubuntu on VM and Windows

I've downloaded all needed sources using `download-sources`, then `make install-all`. Turned out there is a lack of some libs in system, but single `libtool` installation (with refs) fixed all missings. So, again, `make install-all`, `make` is working heavily, lot of output comes and after few minutes I'm getting:

`libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.`
`libtoolize:   error: linking '/usr/share/libtool/build-aux/ltmain.sh' to 'config/' failed`
`libtoolize: You should add the contents of the following files to 'aclocal.m4':`
`libtoolize:   '/usr/share/aclocal/libtool.m4'`
`libtoolize:   '/usr/share/aclocal/ltoptions.m4'`
`libtoolize:   '/usr/share/aclocal/ltsugar.m4'`
`libtoolize:   '/usr/share/aclocal/ltversion.m4'`
`libtoolize:   '/usr/share/aclocal/lt~obsolete.m4'`
`libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,`
`libtoolize: and rerunning libtoolize and aclocal.`
`libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.`
`make[1]: *** [Makefile:199: g7221] Error 1`
`make[1]: Leaving directory '/media/shared_vm/libbaresip-android'`
`make: *** [Makefile:387: install-all] Error 2`

tried running `make` with `sudo`, didn't worked. tried to create `aclocal.m4` as suggested in output

`cat /usr/share/aclocal/libtool.m4 /usr/share/aclocal/ltoptions.m4 /usr/share/aclocal/ltsugar.m4 /usr/share/aclocal/ltversion.m4 /usr/share/aclocal/lt~obsolete.m4 >> aclocal.m4`

also didn't worked (is this even proper approach/output path?). I don't have much background in Linux environment, don't know how to handle this problem, where to look for cause...

Can I ask for some help in building these libs? Maybe there is a lack of some additional dependency installation in readme (just like `libtool`)

**Comment by juha-h** [comment]
Debian libtool package has those files (e.g. /usr/share/aclocal/libtool.m4).  Don't know about Ubuntu.

**Comment by snachmsm** [comment]
Got this lib working, built under Debian 11, which hasn't any issues with build process (besides lack of some basic libs like git, cmake etc. + too low ram for VM, needed at least 2 Gb).

Some notice: in CMakeLists you are pointing on `distribution.video` folder, but makefile and also Android Studio project supposing just `distribution`

Awesome work with this lib, thank you!

**Comment by juha-h** [comment]
snachmsm writes:

> Got this lib working, built under Debian 11, which hasn't any issues
> with build process (besides lack of some basic libs like git, cmake
> etc. + too low ram for VM, needed at least 2 Gb).

Thanks for the update.

> Some notice: in CMakeLists you are pointing on `distribution.video` folder, but makefile and also Android Studio project supposing just `distribution`

When you run `make install-all` in video branch, the libs and include
files will get installed in distrbution.video folder that is used in
baresip-studio video branch CMakeLists.txt.
