### ISSUE TITLE
Add support for different archs than arm_v7a

### ISSUE THREAD

**Issue by anri-vin** [juha-h/libbaresip-android#2]
It would be great if you will add support of building baresip not only for arm_v7a but also for arm64_v8a, x86 and x86_64. I tried to modify Makefile by myself but I'm not familiar with it and arm arch hardcoded in many places in different ways (arm, armv7, arm_v7a etc) and I have no ideas how to deal with it. Thank you in advance. )

**Comment by anri-vin** [comment]
I've made my own build script (on basis of yours) to match my requirements. I switched to NDK19, removed deprecated toolchain generation step and added multiarch (armv7, arm64, x86, x86_64) build. You can take a look on my implementation and improve your script if you find it usefull:
https://github.com/anri-vin/libbaresip_android

**Comment by juha-h** [comment]
Andrei Vinogradov writes:

> I've made my own build script (on basis of yours) to match my
> requirements. I switched to NDK19, removed deprecated toolchain
> generation step and added multiarch (armv7, arm64, x86, x86_64)
> build. You can take a look on my implementation and improve your
> script if you find it usefull:

> https://github.com/anri-vin/libbaresip_android

Thanks. It looks very clean.  I'll try to change mine based on it.  I'm
also at present in the process of adding video support based on ffmpeg.
