### ISSUE TITLE
'absl/meta/type_traits.h' file not found

### ISSUE THREAD

**Issue by ludovicroland** [juha-h/libbaresip-android#20]
Hello,

I am trying to build baresip in order to use it into an Android application. Unfortunately, the build fails.

I am trying to setup a pipeline running on Ubuntu 20.04. From the README file, the steps 1, 2 and 3 seems to work, but my pipeline failed on the step 4.

To launch this step, I am using the following command:

```bash
make install-all NDK_PATH='/usr/local/lib/android/sdk/ndk-bundle' OUTPUT_DIR='distribution'
```

But it fails with the following message:

>make[2]: Entering directory '/home/vsts/work/1/s/webrtc'
[armeabi-v7a] Compile++ thumb: webrtc <= aecm_core.cc
In file included from jni/src/webrtc/modules/audio_processing/aecm/aecm_core.cc:24:
jni/src/webrtc/rtc_base/checks.h:57:10: fatal error: 'absl/meta/type_traits.h' file not found
#include "absl/meta/type_traits.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [/usr/local/lib/android/sdk/ndk/21.4.7075529/build/core/build-binary.mk:478: obj/local/armeabi-v7a/objs/webrtc/src/webrtc/modules/audio_processing/aecm/aecm_core.o] Error 1
make[2]: Leaving directory '/home/vsts/work/1/s/webrtc'
make[1]: *** [Makefile:247: webrtc] Error 2
make[1]: Leaving directory '/home/vsts/work/1/s'
make: *** [Makefile:324: install-all] Error 2
##[error]Bash exited with code '2'.

I am not a C or C++ developer and I have no idea how to fix this issue. Any help is welcome :) Should I update any tools on my pipeline ? Am I missing something from the README file?

Thank you for your help.

**Comment by juha-h** [comment]
The file  'absl/meta/type_traits.h' is included only if __cplusplus is defined:
```
#ifdef __cplusplus
// C++ version.

#include <string>
#include "absl/meta/type_traits.h"
...
```
In my build it is not defined, since I don't get the error.  The file does not even exist in  https://github.com/juha-h/libwebrtc.git mobile branch.

I don't know why it is defined in your build.  Try to add  -U__cplusplus in file webrtc/jni/Android.mk on line like this:
```
common_CFLAGS := -fexceptions -DWEBRTC_POSIX=1 -DWEBRTC_ANDROID -U__cplusplus -I$(LOCAL_PATH)/src/webrtc/
```

**Comment by ludovicroland** [comment]
@juha-h : thank you for your help.

Adding the `-U__cplusplus` option, I still have an error when building the webRTC module. But the error is not the same:

>cd webrtc && \
rm -rf obj && \
/usr/local/lib/android/sdk/ndk-bundle/ndk-build APP_PLATFORM=android-21
make[2]: Entering directory '/home/vsts/work/1/s/webrtc'
[armeabi-v7a] Compile++ thumb: webrtc <= aecm_core.cc
In file included from jni/src/webrtc/modules/audio_processing/aecm/aecm_core.cc:11:
In file included from jni/src/webrtc/modules/audio_processing/aecm/aecm_core.h:17:
In file included from jni/src/webrtc/common_audio/ring_buffer.h:23:
In file included from /usr/local/lib/android/sdk/ndk/21.4.7075529/sources/cxx-stl/llvm-libc++/include/stddef.h:45:
/usr/local/lib/android/sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/9.0.9/include/stddef.h:74:24: error: cannot combine with previous 'int' declaration specifier
typedef __WCHAR_TYPE__ wchar_t;
>
>In file included from jni/src/webrtc/modules/audio_processing/aecm/aecm_core.cc:25:
In file included from jni/src/webrtc/rtc_base/numerics/safe_conversions.h:16:
In file included from /usr/local/lib/android/sdk/ndk/21.4.7075529/sources/cxx-stl/llvm-libc++/include/limits:105:
In file included from /usr/local/lib/android/sdk/ndk/21.4.7075529/sources/cxx-stl/llvm-libc++/include/type_traits:417:
/usr/local/lib/android/sdk/ndk/21.4.7075529/sources/cxx-stl/llvm-libc++/include/cstddef:47:1: error: unknown type name '_LIBCPP_BEGIN_NAMESPACE_STD'
_LIBCPP_BEGIN_NAMESPACE_STD
^
/usr/local/lib/android/sdk/ndk/21.4.7075529/sources/cxx-stl/llvm-libc++/include/cstddef:49:1: error: expected unqualified-id
using ::ptrdiff_t;
^
/usr/local/lib/android/sdk/ndk/21.4.7075529/sources/cxx-stl/llvm-libc++/include/cstddef:60:1: error: unknown type name '_LIBCPP_END_NAMESPACE_STD'
_LIBCPP_END_NAMESPACE_STD
^
In file included from jni/src/webrtc/modules/audio_processing/aecm/aecm_core.cc:25:
In file included from jni/src/webrtc/rtc_base/numerics/safe_conversions.h:16:
In file included from /usr/local/lib/android/sdk/ndk/21.4.7075529/sources/cxx-stl/llvm-libc++/include/limits:105:
/usr/local/lib/android/sdk/ndk/21.4.7075529/sources/cxx-stl/llvm-libc++/include/type_traits:424:28: error: expected ';' after top level declarator
_LIBCPP_BEGIN_NAMESPACE_STD
                           ^
[...]

Any idea on how to fix these new issues?

**Comment by juha-h** [comment]
Ludovic ROLAND writes:

> Adding the `-U__cplusplus` option, I still have an error when building
> the webRTC module. But the error is not the same:

Instead of adding the `-U__cplusplus` option try to change in file
checks.h lines:

#ifdef __cplusplus

to lines:

#ifdef FOOBAR

**Comment by juha-h** [comment]
I found better solution by including absl include files in mobile branch of https://github.com/juha-h/libwebrtc.  Re-install webrtc source:

$ rm -rf webrtc
$ git clone https://github.com/juha-h/libwebrtc.git -b mobile --single-branch webrtc

And then try to make webrtc

$ make webrtc

**Comment by ludovicroland** [comment]
@juha-h : thank you so much. It works perfectly now :)

**Comment by juha-h** [comment]
Thanks for testing.

**Comment by ashellunts** [comment]
FYI, absl lib is usually located in webrtc third_party folder not in root.
