### ISSUE TITLE
make install-all Problems

### ISSUE THREAD

**Issue by nojustbb** [juha-h/libbaresip-android#23]
I do video branch   make install-all,If I find some problems, I can't compile. Do I need to download other packages，it is about to Building ffmpeg-kit library
![1663141053611](https://user-images.githubusercontent.com/27254745/190091284-a9e6031e-ea3b-42f1-ba57-3d94416f2b77.jpg)
![1663141119380](https://user-images.githubusercontent.com/27254745/190091544-23b3cf87-817f-424a-9e73-dac32ac7c5e0.jpg)
![1663141160152](https://user-images.githubusercontent.com/27254745/190091696-9c29c7aa-1c28-4c5c-80c7-2400c9271360.jpg)

**Comment by juha-h** [comment]
Check if you find more info from build.log.  The build works from scratch when F-Droid makes it.

**Comment by nojustbb** [comment]
> android-zlib, libvpx, x264, x265, libaom library，Is it not provided in the project? Do you need to download and compile it yourself，I saw the prompt in the log:Could not find folder for x264
![image](https://user-images.githubusercontent.com/27254745/190106759-8ad180d2-25f9-4746-a292-97bfce5f6b7b.png)

**Comment by juha-h** [comment]
You need to download only those sources that are in download-sources.  ffmpeg make does not currently work with NDK r25,  but does work with r23.
