### ISSUE TITLE
Filed to build libbaresip

### ISSUE THREAD

**Issue by siper** [juha-h/libbaresip-android#26]
I have error building baresiplib in commit [c9dfc84]. Error:
`/home/stersh/StudioProjects/libbaresip-android/re/src/hmac/hmac_sha1.c:58:2: error: missing HMAC-SHA1 backend`

In logs i see:
`-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found version "3.0.8")`

Full log attached.

[make_install_all.log](https://github.com/juha-h/libbaresip-android/files/10138765/make_install_all.log)

**Comment by juha-h** [comment]
I cannot reproduce the issue:
```
[ 15%] Building C object CMakeFiles/re-objs.dir/src/hash/hash.c.o
[ 15%] Building C object CMakeFiles/re-objs.dir/src/hmac/hmac_sha1.c.o
[ 16%] Building C object CMakeFiles/re-objs.dir/src/http/auth.c.o
```
Make sure you have latest openssl-3.0 and re main branch sources.

**Comment by siper** [comment]
Yes, i download sources with `make download-sources` command. I check re and openssl braches, all ok. But it don't compile. Maybe problem with openssl, i install dev version with apt? Or wrong ndk version, i use 25.1.8937393 version?

**Comment by juha-h** [comment]
`make download-sources` downloads openssl branch openssl-3.0, which is the one to use.  I use the same ndk version as you.

**Comment by siper** [comment]
I reinstall latest Ubuntu and it builds. Thanks, i close issue.
