### ISSUE TITLE
The correct way for defining G722 in account file/resource, and config

### ISSUE THREAD

**Issue by assegaf** [juha-h/libbaresip-android#27]
I have done the setup of G729 using BG729 and your library. But I search nowhere for defining the account file for accepting G729.
currently I use audio_codecs="G722/16000/1,PCMU/8000/1,G729/8000/1"
in config file;

and in account fine I have defined 3 codecs, 

module g711.so
module g722.so
module g729.so

and I see BSLibe log (android), I dont see "module: g729 loaded " line log.

12-28 18:04:26.256  4382  4857 D BSLib   : aucodec: PCMU/8000/1
12-28 18:04:26.257  4382  4857 D BSLib   : aucodec: PCMA/8000/1
12-28 18:04:26.257  4382  4857 D BSLib   : module: pcmu loaded, pcma loaded
12-28 18:04:26.257  4382  4857 D BSLib   : aucodec: G722/16000/1
12-28 18:04:26.257  4382  4857 D BSLib   : module: g722  loaded
12-28 18:04:26.257  4382  4857 D BSLib   : aucodec: G729/8000/1

G722 and PCMU is working fine, except G729 still being rejected / transcoded by sip/media server.

have I wrote correct configuration file in account/config file ?

when I force to G729 only in sip server /ippbx server.

12-28 18:16:39.845  4382  4855 I Baresip Service: got uaEvent call closed,No audio codecs/sip:324647716945@192.168.20.XXX/2377312776 AoR sip:324647716945@192.168.20.XXX call 2377312776 that is will be closed is not found,

It seem my audio codec not recognized by libbaresip-android,.

**Comment by juha-h** [comment]
Looks like your config is correct.  Check with -s option if G729 is
included in invite.

**Comment by assegaf** [comment]
yes, I thought so, all is correct in BS, its the IP PBX who doing wrong things. I just know it by now. Oh Why g729 exist in the world full of open source and everybody use it ... 

closed

**Comment by assegaf** [comment]
I am able to compile bcg729 in libbaresip module g729, 

but I am not able to compile support g729 with bcg729 in asterisk ip pbx server. I choose bcg729 because the linux server is ARMV8 machine.
