### ISSUE TITLE
GSM module in baresip

### ISSUE THREAD

**Issue by AviWA** [juha-h/libbaresip-android#29]
I have seen that you have added gsm module in libbaresip i have successfully built the baresip project in android studio after that in the app i dont see any option that used to make gsm calls. How can i use that module tell me how to integrate gsm module to the project.

Thanks.

**Comment by juha-h** [comment]
AviWA writes:

> I have seen that you have added gsm module in libbaresip i have
> successfully built the baresip project in android studio after that in
> the app i dont see any option that used to make gsm calls. How can i
> use that module tell me how to integrate gsm module to the project.

You have to activate GSM codec in account's Audio Codecs.
