### ISSUE TITLE
Error While  make install-all

### ISSUE THREAD

**Issue by sagarmagnatesage** [juha-h/libbaresip-android#3]
I have configured Makefile with my local ndk path and other required changes too.
Also, download sources successfully,
Now when I and trying to perform the next step it shows me the following error.
I am using **cygwin** with windows system for the Linux environment.

$ make install-all
make install ANDROID_TARGET_ARCH=armeabi-v7a
make[1]: Entering directory '/cygdrive/E/sagar/Work/BackUps/SIP_VOIP/libbaresip-android-master'
make distclean -C openssl
make[2]: Entering directory '/cygdrive/E/sagar/Work/BackUps/SIP_VOIP/libbaresip-android-master/openssl'
make[2]: *** No rule to make target 'distclean'.  Stop.
make[2]: Leaving directory '/cygdrive/E/sagar/Work/BackUps/SIP_VOIP/libbaresip-android-master/openssl'
make[1]: [Makefile:108: openssl] Error 2 (ignored)
cd openssl && \
CC=clang ANDROID_NDK=E:/Softs/android_studio_sdk_3.3.2/ndk-bundle PATH=E:/Softs/android_studio_sdk_3.3.2/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin:/usr/bin:/bin ./Configure android-arm no-shared -D__ANDROID_API__=21 && \
CC=clang ANDROID_NDK=E:/Softs/android_studio_sdk_3.3.2/ndk-bundle PATH=E:/Softs/android_studio_sdk_3.3.2/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin:/usr/bin:/bin make build_libs
Configuring OpenSSL version 3.0.0-dev for target android-arm
Using os-specific seed configuration
no NDK clang on $PATH at (eval 7) line 121.
make[1]: *** [Makefile:109: openssl] Error 2
make[1]: Leaving directory '/cygdrive/E/sagar/Work/BackUps/SIP_VOIP/libbaresip-android-master'
make: *** [Makefile:200: install-all] Error 2

Please help.

**Comment by juha-h** [comment]
Sagar Thakarar writes:

> I have configured Makefile with my local ndk path and other required
> changes too. 
> Also, download sources successfully,
> Now when I and trying to perform the next step it shows me the
> following error.
> I am using **cygwin** with windows system for the Linux environment.

I don't know (and don't want to know) anything about windows.

This error message tells what your problem is:

> no NDK clang on $PATH at (eval 7) line 121.

clang needs to be found in directory

$(NDK_PATH)/toolchains/llvm/prebuilt/linux-x86_64/bin
