### ISSUE TITLE
Integrate libbaresip into android studio project

### ISSUE THREAD

**Issue by AviWA** [juha-h/libbaresip-android#31]
I wanna integrate the libbaresip to my android studio project not to baresip-studio project. How to do this.

I want to get the files into my project like baresip studio project and able to call the c/c++ methods from java or kotlin that means i need to make alternate the baresip project.

**Comment by juha-h** [comment]
Sorry, but I don't have resources to help how people use the lib with their projects.  There is lots of information on the Internet on how to integrate native code to Android apps.
