### ISSUE TITLE
beep/ voice play at start or receiving voice call. 

### ISSUE THREAD

**Issue by assegaf** [juha-h/libbaresip-android#33]
hi juha, thanks for all your hardwork.

its possible to play wav file or beep, or like answering machine /introduction on exactly at start of time of receiving voice call ?

**Comment by juha-h** [comment]
I suggest you ask this from baresip project.  If there is, then you can apply the same method in your Android app.

**Comment by juha-h** [comment]
Din writes:

> thanks, I think its very hard to add, since audio already openned, and
> microphone cannot be inserted directly by wav file in android
> device. I am thinking the only way is form softswitch/sip server

Perhaps you could use early media (183 Session Progress).

**Comment by assegaf** [comment]
thanks got, it
