### ISSUE TITLE
Wanna make libbaresip directly use alsa driver instead of opensl es

### ISSUE THREAD

**Issue by AviWA** [juha-h/libbaresip-android#36]
Hi ,
I wanna make libbaresip-android directly use alsa driver instead of opensl es when i am using baresip linux I am getting alsa.so module not found error 

dl: mod: ./alsa.so (./alsa.so: cannot open shared object file: No such file or directory)
module alsa.so: No such file or directory [2]

**Comment by AviWA** [comment]
When building libbaresip-android for baresip-studio i can get all the files u mentioned in readme file but alsa file is not able to build when build for baresip linux also i got the alsa not found error

**Comment by juha-h** [comment]
baresip libarary of this repo does not use alsa module.  If you want to use it, you need to fork the repo and implement it.
