### ISSUE TITLE
Alsa header file not found

### ISSUE THREAD

**Issue by AviWA** [juha-h/libbaresip-android#37]
When building libbaresip-android I am encountering this issue i have successfully built alsa drivers in my linux but still it is getting. Libbaresip project compiler cant find alsa header files. 

https://github.com/juha-h/libbaresip-android/assets/123717548/e1d0168a-d9fe-4341-b0ae-209dc2f56313

**Comment by juha-h** [comment]
As I have already written, libbaresip-android project does not include alsa module.
