### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by xiezhouyan1027** [juha-h/libbaresip-android#41]
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by opencore-amr configure 0.1.6, which was
generated by GNU Autoconf 2.71.  Invocation command line was

  $ ./configure --host=arm-linux-androideabi --disable-shared CXXFLAGS=-fPIC --prefix=/opt/baresip/libbaresip-android/amr

## --------- ##

hostname = xzy
uname -m = i686
uname -r = 6.1.0-21-686-pae
uname -s = Linux
uname -v = #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03)

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = i686
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /opt/Android/ndk//toolchains/llvm/prebuilt/linux-x86_64/bin/
PATH: /usr/bin/
PATH: /bin/

## ----------- ##

configure:2932: looking for aux files: config.guess config.sub ltmain.sh compile missing install-sh
configure:2945:  trying ././
configure:2974:   ././config.guess found
configure:2974:   ././config.sub found
configure:2974:   ././ltmain.sh found
configure:2974:   ././compile found
configure:2974:   ././missing found
configure:2956:   ././install-sh found
configure:3105: checking for a BSD-compatible install
configure:3178: result: /usr/bin/install -c
configure:3189: checking whether build environment is sane
configure:3244: result: yes
configure:3300: checking for arm-linux-androideabi-strip
configure:3335: result: no
configure:3345: checking for strip
configure:3366: found /usr/bin/strip
configure:3377: result: strip
configure:3403: checking for a race-free mkdir -p
configure:3447: result: /usr/bin/mkdir -p
configure:3454: checking for gawk
configure:3489: result: no
configure:3454: checking for mawk
configure:3475: found /usr/bin/mawk
configure:3486: result: mawk
configure:3497: checking whether make sets $(MAKE)
configure:3520: result: yes
configure:3550: checking whether make supports nested variables
configure:3568: result: yes
configure:3653: checking whether UID '0' is supported by ustar format
configure:3656: result: yes
configure:3663: checking whether GID '0' is supported by ustar format
configure:3666: result: yes
configure:3674: checking how to create a ustar tar archive
configure:3685: tar --version
tar (GNU tar) 1.34
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
configure:3688: $? = 0
configure:3728: tardir=conftest.dir && eval tar --format=ustar -chf - "$tardir" >conftest.tar
configure:3731: $? = 0
configure:3735: tar -xf - <conftest.tar
configure:3738: $? = 0
configure:3740: cat conftest.dir/file
GrepMe
configure:3743: $? = 0
configure:3757: result: gnutar
configure:3833: checking whether make supports nested variables
configure:3851: result: yes
configure:3863: checking whether to enable maintainer-specific portions of Makefiles
configure:3873: result: no
configure:4097: checking for C++ compiler version
configure:4106: armv7a-linux-androideabi23-clang++ --version >&5
./configure: line 4108: armv7a-linux-androideabi23-clang++: command not found
configure:4117: $? = 127
configure:4106: armv7a-linux-androideabi23-clang++ -v >&5
./configure: line 4108: armv7a-linux-androideabi23-clang++: command not found
configure:4117: $? = 127
configure:4106: armv7a-linux-androideabi23-clang++ -V >&5
./configure: line 4108: armv7a-linux-androideabi23-clang++: command not found
configure:4117: $? = 127
configure:4106: armv7a-linux-androideabi23-clang++ -qversion >&5
./configure: line 4108: armv7a-linux-androideabi23-clang++: command not found
configure:4117: $? = 127
configure:4137: checking whether the C++ compiler works
configure:4159: armv7a-linux-androideabi23-clang++ -fPIC   conftest.cpp  >&5
./configure: line 4161: armv7a-linux-androideabi23-clang++: command not found
configure:4163: $? = 127
configure:4203: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "opencore-amr"
| #define PACKAGE_TARNAME "opencore-amr"
| #define PACKAGE_VERSION "0.1.6"
| #define PACKAGE_STRING "opencore-amr 0.1.6"
| #define PACKAGE_BUGREPORT "http://sourceforge.net/projects/opencore-amr/"
| #define PACKAGE_URL ""
| #define PACKAGE "opencore-amr"
| #define VERSION "0.1.6"
| /* end confdefs.h.  */
| 
| int
| main (void)
| {
| 
|   ;
|   return 0;
| }
configure:4208: error: in `/opt/baresip/libbaresip-android/amr':
configure:4210: error: C++ compiler cannot create executables
See `config.log' for more details

## ---------------- ##

ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_set=set
ac_cv_env_CC_value='armv7a-linux-androideabi23-clang --sysroot /opt/Android/ndk//toolchains/llvm/prebuilt/linux-x86_64/sysroot'
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CXXCPP_set=
ac_cv_env_CXXCPP_value=
ac_cv_env_CXXFLAGS_set=set
ac_cv_env_CXXFLAGS_value=-fPIC
ac_cv_env_CXX_set=set
ac_cv_env_CXX_value=armv7a-linux-androideabi23-clang++
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_LT_SYS_LIBRARY_PATH_set=
ac_cv_env_LT_SYS_LIBRARY_PATH_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=set
ac_cv_env_host_alias_value=arm-linux-androideabi
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/usr/bin/mkdir
ac_cv_prog_AWK=mawk
ac_cv_prog_ac_ct_STRIP=strip
ac_cv_prog_make_make_set=yes
am_cv_make_support_nested_variables=yes
am_cv_prog_tar_ustar=gnutar

## ----------------- ##

ACLOCAL='${SHELL} '\''/opt/baresip/libbaresip-android/amr/missing'\'' aclocal-1.16'
AMDEPBACKSLASH=''
AMDEP_FALSE=''
AMDEP_TRUE=''
AMRNB_DECODER_FALSE='#'
AMRNB_DECODER_TRUE=''
AMRNB_ENCODER_FALSE='#'
AMRNB_ENCODER_TRUE=''
AMTAR='$${TAR-tar}'
AM_BACKSLASH='\'
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='0'
AM_V='$(V)'
AR='llvm-ar'
AUTOCONF='${SHELL} '\''/opt/baresip/libbaresip-android/amr/missing'\'' autoconf'
AUTOHEADER='${SHELL} '\''/opt/baresip/libbaresip-android/amr/missing'\'' autoheader'
AUTOMAKE='${SHELL} '\''/opt/baresip/libbaresip-android/amr/missing'\'' automake-1.16'
AWK='mawk'
CC='armv7a-linux-androideabi23-clang --sysroot /opt/Android/ndk//toolchains/llvm/prebuilt/linux-x86_64/sysroot'
CCDEPMODE=''
CFLAGS=''
COMPILE_AS_C_FALSE='#'
COMPILE_AS_C_TRUE=''
CPPFLAGS=''
CSCOPE='cscope'
CTAGS='ctags'
CXX='armv7a-linux-androideabi23-clang++'
CXXCPP=''
CXXDEPMODE=''
CXXFLAGS='-fPIC'
CYGPATH_W='echo'
DEFS=''
DEPDIR=''
DLLTOOL=''
DSYMUTIL=''
DUMPBIN=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
ETAGS='etags'
EXAMPLES_FALSE=''
EXAMPLES_TRUE='#'
EXEEXT=''
FGREP=''
FILECMD=''
GCC_ARMV5_FALSE=''
GCC_ARMV5_TRUE='#'
GREP=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
LD=''
LDFLAGS=''
LIBOBJS=''
LIBS=''
LIBTOOL=''
LIPO=''
LN_S=''
LTLIBOBJS=''
LT_SYS_LIBRARY_PATH=''
MAINT='#'
MAINTAINER_MODE_FALSE=''
MAINTAINER_MODE_TRUE='#'
MAKEINFO='${SHELL} '\''/opt/baresip/libbaresip-android/amr/missing'\'' makeinfo'
MANIFEST_TOOL=''
MKDIR_P='/usr/bin/mkdir -p'
NM=''
NMEDIT=''
OBJDUMP=''
OBJEXT=''
OPENCORE_AMRNB_VERSION=''
OPENCORE_AMRWB_VERSION=''
OTOOL64=''
OTOOL=''
PACKAGE='opencore-amr'
PACKAGE_BUGREPORT='http://sourceforge.net/projects/opencore-amr/'
PACKAGE_NAME='opencore-amr'
PACKAGE_STRING='opencore-amr 0.1.6'
PACKAGE_TARNAME='opencore-amr'
PACKAGE_URL=''
PACKAGE_VERSION='0.1.6'
PATH_SEPARATOR=':'
RANLIB='llvm-ranlib'
SED=''
SET_MAKE=''
SHELL='/bin/bash'
STRIP='strip'
VERSION='0.1.6'
ac_ct_AR=''
ac_ct_CC=''
ac_ct_CXX=''
ac_ct_DUMPBIN=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__fastdepCXX_FALSE=''
am__fastdepCXX_TRUE=''
am__include=''
am__isrc=''
am__leading_dot='.'
am__nodep=''
am__quote=''
am__tar='tar --format=ustar -chf - "$$tardir"'
am__untar='tar -xf -'
bindir='${exec_prefix}/bin'
build=''
build_alias=''
build_cpu=''
build_os=''
build_vendor=''
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host='arm-linux-androideabi'
host_alias='arm-linux-androideabi'
host_cpu=''
host_os=''
host_vendor=''
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /opt/baresip/libbaresip-android/amr/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='$(MKDIR_P)'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/opt/baresip/libbaresip-android/amr'
program_transform_name='s,x,x,'
psdir='${docdir}'
runstatedir='${localstatedir}/run'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "opencore-amr"
#define PACKAGE_TARNAME "opencore-amr"
#define PACKAGE_VERSION "0.1.6"
#define PACKAGE_STRING "opencore-amr 0.1.6"
#define PACKAGE_BUGREPORT "http://sourceforge.net/projects/opencore-amr/"
#define PACKAGE_URL ""
#define PACKAGE "opencore-amr"
#define VERSION "0.1.6"

configure: exit 77

**Comment by juha-h** [comment]
Sorry, but the issue must be directly related to the Makefile of this project.

**Comment by xiezhouyan1027** [comment]
debian 11, ndk 26 , cmake 3.25.1。
How do I modify configuration Makefile？ thank you.

**Comment by juha-h** [comment]
Show what happens when you give commands
```
make download-sources
make amr
```

**Comment by xiezhouyan1027** [comment]
make download-sources  success，but make amr error 
![image](https://github.com/juha-h/libbaresip-android/assets/57662346/7f1ce774-8de5-4162-8916-03dd9d483bbe)

make amr ANDROID_TARGET_ARCH=armeabi-v7a  same error.
Should I configure the makefile?
![image](https://github.com/juha-h/libbaresip-android/assets/57662346/368f8daa-3a18-404c-adb8-23c02955d211)

**Comment by xiezhouyan1027** [comment]
Sorry, I know the cause of the problem. I configured the environment variable of ndk privately, and the version of ndk is different from that in build.gradle. I have revised it and it can be used now. Thank you.
**The ndk path is in /opt/Android/ndk/26.3.11579264.

build.gradle:
 ndkVersion "26.3.11579264"**
