### ISSUE TITLE
OpenSSL Compilation Error (Atomic Operations)

### ISSUE THREAD

**Issue by AviWA** [juha-h/libbaresip-android#45]
This is the log 

In file included from crypto/asn1/a_digest.c:24:
In file included from include/crypto/x509.h:14:
include/internal/refcount.h:33:12: error: address argument to atomic builtin must be a pointer ('int' invalid)
    *ret = atomic_fetch_add_explicit(val, 1, memory_order_relaxed) + 1;
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/10/include/stdatomic.h:195:6: note: expanded from macro 'atomic_fetch_add_explicit'
                          __atomic_fetch_add ((PTR), (VAL), (MO))
                          ^                   ~~~~~
In file included from crypto/asn1/a_digest.c:24:
In file included from include/crypto/x509.h:14:
include/internal/refcount.h:50:12: error: address argument to atomic builtin must be a pointer ('int' invalid)
    *ret = atomic_fetch_sub_explicit(val, 1, memory_order_relaxed) - 1;
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/10/include/stdatomic.h:200:6: note: expanded from macro 'atomic_fetch_sub_explicit'
                          __atomic_fetch_sub ((PTR), (VAL), (MO))
                          ^                   ~~~~~
2 errors generated.

**Comment by juha-h** [comment]
Just did:
```
git clone https://github.com/openssl/openssl.git -b openssl-3.1.0 --single-branch openssl
make openssl
```
and didn't get any errors.
