### ISSUE TITLE
hao to use ndk-bundle that comes with Android Studio 3.4.1 Sdk  

### ISSUE THREAD

**Issue by yuexiajiayan** [juha-h/libbaresip-android#5]
i'm try cmakelist，but openssl\baresip head file have some error

**Comment by juha-h** [comment]
yuexiajiayan writes:

> i'm try cmakelist，but openssl\baresip head file have some error

Only building the lib by following the steps described in README
are supported.

**Comment by juha-h** [comment]
Set NDK_PATH in Makefile according to the comment.
