### ISSUE TITLE
How to correct errors in studio 3.4

### ISSUE THREAD

**Issue by yuexiajiayan** [juha-h/libbaresip-android#6]
i'm add in studio like this:

![1](https://user-images.githubusercontent.com/16077858/62672911-fd903a00-b9ce-11e9-812e-ed378777ecc9.jpg)

CMakeLists.txt ：

cmake_minimum_required(VERSION 3.4.1)

set(distribution_DIR ${CMAKE_SOURCE_DIR}/distribution)

add_library(lib_crypto STATIC IMPORTED)
set_target_properties(lib_crypto PROPERTIES IMPORTED_LOCATION
        ${distribution_DIR}/openssl/lib/${ANDROID_ABI}/libcrypto.a)

add_library(lib_ssl STATIC IMPORTED)
set_target_properties(lib_ssl PROPERTIES IMPORTED_LOCATION
        ${distribution_DIR}/openssl/lib/${ANDROID_ABI}/libssl.a)

add_library(lib_re STATIC IMPORTED)
set_target_properties(lib_re PROPERTIES IMPORTED_LOCATION
        ${distribution_DIR}/re/lib/${ANDROID_ABI}/libre.a)

add_library(lib_rem STATIC IMPORTED)
set_target_properties(lib_rem PROPERTIES IMPORTED_LOCATION
        ${distribution_DIR}/rem/lib/${ANDROID_ABI}/librem.a)

add_library(lib_opus STATIC IMPORTED)
set_target_properties(lib_opus PROPERTIES IMPORTED_LOCATION
        ${distribution_DIR}/opus/lib/${ANDROID_ABI}/libopus.a)

add_library(lib_bn STATIC IMPORTED)
set_target_properties(lib_bn PROPERTIES IMPORTED_LOCATION
        ${distribution_DIR}/bn/lib/${ANDROID_ABI}/libbn.a)

add_library(lib_g7221 STATIC IMPORTED)
set_target_properties(lib_g7221 PROPERTIES IMPORTED_LOCATION
        ${distribution_DIR}/g7221/lib/${ANDROID_ABI}/libg722_1.a)
add_library(lib_ilbc STATIC IMPORTED)
set_target_properties(lib_ilbc PROPERTIES IMPORTED_LOCATION
        ${distribution_DIR}/ilbc/lib/${ANDROID_ABI}/libilbc.a)

add_library(lib_zrtp STATIC IMPORTED)
set_target_properties(lib_zrtp PROPERTIES IMPORTED_LOCATION
        ${distribution_DIR}/zrtp/lib/${ANDROID_ABI}/libzrtp.a)

add_library(lib_webrtc STATIC IMPORTED)
set_target_properties(lib_webrtc PROPERTIES IMPORTED_LOCATION
        ${distribution_DIR}/webrtc/lib/${ANDROID_ABI}/libwebrtc.a)

add_library(lib_baresip STATIC IMPORTED)
set_target_properties(lib_baresip PROPERTIES IMPORTED_LOCATION
        ${distribution_DIR}/baresip/lib/${ANDROID_ABI}/libbaresip.a)

 
add_library(  
        native-lib

       
        SHARED

     
        native-lib.cpp)
 
include_directories(native-lib
        ${distribution_DIR}/baresip/include
        ${distribution_DIR}/re/include
        ${distribution_DIR}/rem/include
        )

find_library(  
        log-lib

        
        log)

 
target_link_libraries(  
        native-lib

        lib_re
        lib_rem
        lib_crypto
        lib_ssl
        lib_opus
        lib_g7221
        lib_ilbc
        lib_webrtc
        lib_baresip

        
        # included in the NDK.
        ${log-lib})

----------------------
but make error

Build command failed.
Error while executing process D:\android\android-sdk-windows\cmake\3.10.2.4988404\bin\cmake.exe with arguments {--build E:\android\studio\baresip\app\.externalNativeBuild\cmake\debug\arm64-v8a --target native-lib}
[1/1] Linking CXX shared library E:\android\studio\baresip\app\build\intermediates\cmake\debug\obj\arm64-v8a\libnative-lib.so
FAILED: E:/android/studio/baresip/app/build/intermediates/cmake/debug/obj/arm64-v8a/libnative-lib.so 
cmd.exe /C "cd . && D:\android\android-sdk-windows\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android26 --gcc-toolchain=D:/android/android-sdk-windows/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=D:/android/android-sdk-windows/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security   -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -Wl,-z,noexecstack -shared -Wl,-soname,libnative-lib.so -o E:\android\studio\baresip\app\build\intermediates\cmake\debug\obj\arm64-v8a\libnative-lib.so CMakeFiles/native-lib.dir/native-lib.cpp.o  E:/android/studio/baresip/app/src/main/cpp/distribution/re/lib/arm64-v8a/libre.a E:/android/studio/baresip/app/src/main/cpp/distribution/rem/lib/arm64-v8a/librem.a E:/android/studio/baresip/app/src/main/cpp/distribution/openssl/lib/arm64-v8a/libcrypto.a E:/android/studio/baresip/app/src/main/cpp/distribution/openssl/lib/arm64-v8a/libssl.a E:/android/studio/baresip/app/src/main/cpp/distribution/opus/lib/arm64-v8a/libopus.a E:/android/studio/baresip/app/src/main/cpp/distribution/g7221/lib/arm64-v8a/libg722_1.a E:/android/studio/baresip/app/src/main/cpp/distribution/ilbc/lib/arm64-v8a/libilbc.a E:/android/studio/baresip/app/src/main/cpp/distribution/webrtc/lib/arm64-v8a/libwebrtc.a E:/android/studio/baresip/app/src/main/cpp/distribution/baresip/lib/arm64-v8a/libbaresip.a -llog -latomic -lm && cd ."
E:/android/studio/baresip/app/src/main/cpp/distribution/openssl/lib/arm64-v8a/libssl.a(ssl_ciph.o): In function `ssl_cipher_get_evp':
ssl_ciph.c:(.text+0x7bc): undefined reference to `EVP_enc_null'
E:/android/studio/baresip/app/src/main/cpp/distribution/openssl/lib/arm64-v8a/libssl.a(ssl_ciph.o): In function `SSL_COMP_add_compression_method':
ssl_ciph.c:(.text+0x2d48): undefined reference to `COMP_get_type'
E:/android/studio/baresip/app/src/main/cpp/distribution/openssl/lib/arm64-v8a/libssl.a(ssl_ciph.o): In function `SSL_COMP_get_name':
ssl_ciph.c:(.text+0x2ed4): undefined reference to `COMP_get_name'
E:/android/studio/baresip/app/src/main/cpp/distribution/openssl/lib/arm64-v8a/libssl.a(ssl_ciph.o): In function `do_load_builtin_compressions_ossl_':
ssl_ciph.c:(.text+0x34ec): undefined reference to `COMP_get_type'
ssl_ciph.c:(.text+0x3528): undefined reference to `COMP_get_name'
E:/android/studio/baresip/app/src/main/cpp/distribution/openssl/lib/arm64-v8a/libssl.a(ssl_lib.o): In function `SSL_clear':
ssl_lib.c:(.text+0x28c): undefined reference to `COMP_CTX_free'
ssl_lib.c:(.text+0x298): undefined reference to `COMP_CTX_free'
E:/android/studio/baresip/app/src/main/cpp/distribution/openssl/lib/arm64-v8a/libssl.a(ssl_lib.o): In function `SSL_free':
ssl_lib.c:(.text+0xa1c): undefined reference to `COMP_CTX_free'
ssl_lib.c:(.text+0xa28): undefined reference to `COMP_CTX_free'
ssl_lib.c:(.text+0xb78): undefined reference to `ASYNC_WAIT_CTX_free'

and others。

References to modules could not be found 。i'm error??

**Comment by juha-h** [comment]
I only know how to use the lib in my Android baresip app https://github.com/juha-h/baresip-studio.  See its CMakeLists.txt for clues.  Perhaps target_link_libraries order is not correct.  I haven't tried to mix static and shared libs.
