### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by OumaSyuu** [juha-h/libbaresip-android#7]
Error by following step 1: 

`Cloning into 'libbaresip-android'...`
`remote: Repository not found.`
`fatal: repository 'https://github.com/juha-g/libbaresip-android.git/' not found`

Considering this project names as "juha-h/libbaresip-android". Could it be 
`$ git clone https://github.com/juha-h/libbaresip-android.git`
?

**Comment by juha-h** [comment]
Thanks, will fix.

**Comment by juha-h** [comment]
Fixed.
