### ISSUE TITLE
build system seems to assume Linux

### ISSUE THREAD

**Issue by gdt** [juha-h/libbaresip-android#8]
I have Android Studio and NDK on a Mac.  I am able to build a variety of things.   After following the instructions, the build fails in openssl looking for linux binaries, which are not there and would not run that well anyway.   I do find a `prebuilt/darwin-x86_64/bin`.  After patching linux to darwin a few places, it seems to start going.   So I suggest that in the place the user has to configure, there is a variable for build host, or perhaps use uname?

```
CC=clang ANDROID_NDK=/path_to_bundle/ndk-bundle PATH=/path_to_bundle/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin:/usr/bin:/bin ./Configure android
-arm64 no-shared -D__ANDROID_API__=21
```

**Comment by juha-h** [comment]
There is now:
```
OS		:= linux
HOST_OS		:= linux-x86_64
```
Are you suggesting that one or both of these lines be moved to `VALUES TO CONFIGURE` section?

**Comment by gdt** [comment]
I am unclear if OS is for the target, in which case no it's not configurable.  But HOST_OS yes should be in the section for the user to configure.   There may then be a few things that should be switched on it instead of just open-coded, but moving it into the configurable section would be a good start and make it easier.

**Comment by juha-h** [comment]
How about this:
```
OS        := $(shell uname -s | tr "[A-Z]" "[a-z]")

ifeq ($(OS),linux)
	HOST_OS   := linux-x86_64
endif
ifeq ($(OS),darwin)
	HOST_OS   := darwin-x86_64
endif
```

**Comment by gdt** [comment]
Sure, that looks like useful progress.

**Comment by juha-h** [comment]
I pushed the change.

**Comment by juha-h** [comment]
I'll close this now.  Reopen if the issue still persists.  I don't have access to Mac OS, so better to also provide a pull request.
