### ISSUE TITLE
build system discards user path, where libtoolize might be

### ISSUE THREAD

**Issue by gdt** [juha-h/libbaresip-android#9]
The path is hard set to the NDK and /usr/bin and /bin, but on Macs typically one installs autotools etc. via some package manager.  I use pkgsrc, in /opt/pkg, but  /opt/pkg/bin is discarded and thus the build in tiff failed with 
```
+ libtoolize --force --copy
./autogen.sh: line 3: libtoolize: command not found
```
but it is in /opt/pkg/bin/libtoolize, just where I expect it.

The fix is not obvious; perhaps PATH stuff should be in the config.  Or perhaps the user's PATH respected, with just an NDK prepend.  That's kind of like Linux in effect, which has a culture of putting everything in /usr/bin, which feels much like letting the user's multiple directories work.

**Comment by gdt** [comment]
After adding /opt/pkg/bin to the setting of PATH (not mergeable I know), the build gets much further.

**Comment by juha-h** [comment]
Greg Troxel writes:

> After adding /opt/pkg/bin to the setting of PATH (not mergeable I
> know), the build gets much further.

If you get the Makefile working for Mac, then create a pull request, I'm
myself only a Linux person and don't know (and don't want to know)
anything about proprietary OSes.  You may get help from the NDK
community.

**Comment by juha-h** [comment]
I'll close this due to inactivity.

**Comment by gdt** [comment]
Is there any reason to believe this is fixed, or was incorrect?   Or you just don't things in the tracker that you aren't interested in working on?   This does seem like a useful hint for anyone trying to build on a mac.

**Comment by juha-h** [comment]
I would be glad to merge a pull request, but I myself cannot do anything about this, since (as I mentioned), I live in Linux world.  So currently, build on MacOS is not supported if it does not work using the Makefile as is.
